# Generated by Django 4.1.1 on 2023-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
