# Generated by Django 4.1.1 on 2023-09-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Employed', 'Employed'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
    ]
