# Generated by Django 4.1.1 on 2023-09-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaton',
            name='Notificaton_type',
            field=models.TextField(choices=[('message', 'message'), ('applicaton', 'applicaton')], max_length=28),
        ),
    ]
